### PR TITLE
fix CMakeLists.txt to compile on Gentoo Linux

### PR DESCRIPTION
**Pull request by smunix**
Fix LLVM component dependencies for linking on Gentoo (tested on Sabayon) Linux

### CODE REVIEW

**Comment by kthielen** [comment]
Just out of curiosity, what’s the story with Gentoo?  Should I use this distro?  At the moment I just use Fedora and macOS at home.

**Comment by salumup** [comment]
Nothing special about Gentoo, llvm-3.5 has been deco'ed on it and I'm hearing the same story from Linux Mint (which Michel is using)

**Comment by kthielen** [comment]
Somehow this change broke my local Mac builds (first time I've done a clean rebuild from cmake).  I'm not sure why there's so much churn on this cmake config, always seems to have issues.  :T

**Comment by smunix** [comment]
> Somehow this change broke my local Mac builds (first time I've done a clean rebuild from cmake). I'm not sure why there's so much churn on this cmake config, always seems to have issues. :T

I might need to add a branch to check llvm versions in cmake. What version are you using on your Mac ? If I'm not mistaken, Travis only builds with llvm-4.0 ?

**Pull request merged**
