### PR TITLE
search for equivalent DFA states faster in compile-time

### PR DESCRIPTION
**Pull request by chenkai036**
This change resolves the issue #280, which uses a disjoint set to store
the equivalence DFA states found in the search and to reduce the total
number of iterations in compiling regex eventually.  Instead of looping
over all the combinations in DFA states in each run, the search space
shall shrink because the number of equivalence classes in the set are
getting smaller.

As a minor performance improvement, the range mapping is created only
when necessary in the search algorithm.

### CODE REVIEW

**Comment by chenkai036** [comment]
A simplified perf results show a large DFA with initial ~16K states can be compiled in about 3 mins (whereas earlier it was 15+ mins).  Each line shows how the number of equivalence classes changes and its execution time.  What makes me curious is the call `findEquivStates` seems to be invoked twice even though I tested only one match expression (the number looks similar but not exactly the same).

```
equiv size = 16759 time: 22.0802s
equiv size = 14733 time: 15.3659s
equiv size = 12885 time: 10.5827s
equiv size = 11104 time: 9.48993s
equiv size = 9350  time: 5.83303s
equiv size = 7740  time: 3.8986s
equiv size = 6584  time: 3.04657s
equiv size = 6360  time: 2.81656s
equiv size = 6322  time: 2.76983s
equiv size = 6287  time: 2.70955s
equiv size = 6252  time: 2.66524s
equiv size = 6225  time: 2.65313s
equiv size = 6198  time: 2.64039s
equiv size = 6171  time: 2.60692s
equiv size = 6152  time: 2.58309s
equiv size = 6150  time: 2.5845s
equiv compress done
equiv size = 16769 time: 21.8915s
equiv size = 14743 time: 15.3736s
equiv size = 12895 time: 10.4182s
equiv size = 11114 time: 9.40876s
equiv size = 9360  time: 5.78632s
equiv size = 7750  time: 3.92095s
equiv size = 6594  time: 3.08088s
equiv size = 6370  time: 2.82939s
equiv size = 6332  time: 2.81447s
equiv size = 6297  time: 2.78181s
equiv size = 6262  time: 2.73236s
equiv size = 6235  time: 2.70565s
equiv size = 6208  time: 2.70426s
equiv size = 6181  time: 2.6664s
equiv size = 6162  time: 2.6634s
equiv size = 6160  time: 2.62692s
equiv compress done
```

**Comment by kthielen** [comment]
This will be a great change, I know there are a couple of use-cases where the existing compile-time overhead is painful.

Do you have a rough idea of what the compile-time improvement looks like?

I'd like to read your change in more detail later tonight.  It looks like a good idea that you'll reduce the set of state pairs that you look at in each cycle of the DFA reduction process.  But this way will you still revisit old state pairs that previously weren't considered equivalent?  It can take a while to figure out that two states are equivalent.

It looks like you've thought this through carefully so I'm more asking just for my own understanding.

**Comment by kthielen** [comment]
Posted at the same time, that looks like a really great improvement!  On the question of being invoked twice, do you think that the whole pattern match translation is happening twice?  It might just be some naive old code in the parser that decides to run the whole process twice for whatever reason.

**Comment by chenkai036** [comment]
> I'd like to read your change in more detail later tonight. It looks like a good idea that you'll reduce the set of state pairs that you look at in each cycle of the DFA reduction process. But this way will you still revisit old state pairs that previously weren't considered equivalent? It can take a while to figure out that two states are equivalent.

Each DFA state `x` is initially in its own independent equivalence class by setting `representative[x] = x`.  Later this property will get updated and the chain of representatives will be compressed when two equivalent states are merged.  The `compression` method will keep the representatives of each equivalence class, resulting in a refined set of classes that are considered as disjoint so far.

**Comment by chenkai036** [comment]
> On the question of being invoked twice, do you think that the whole pattern match translation is happening twice? It might just be some naive old code in the parser that decides to run the whole process twice for whatever reason.

I haven't tracked it down yet, mark #282 as a follow-up item.

**Comment by smunix** [comment]
Love this ! Using disjoint set + compression is a clever trick !

**Comment by chenkai036** [comment]
I begin to realize, and if I understand it correctly, what we are looking for is to find all the strongly connected components.  After the first round of computation within the while-loop, the `bit_table` has actually defined an 0-1 adjacency matrix for the DFA states.  With that squared matrix, I think we can possibly bootstrap the entire connected components out of it by multiplying itself.  Recall that the definition of matrix multiplication (as below), in our situation, _A(i, j)_ is positive if there is a path from state _i_ to state _j_, meaning both states are in the same connected component.  If _A(i, j)_ is positive, we set its value as 1, otherwise _A(i, j)_ is 0.  We can keep multiplying the matrix until its product reaches a fixed point.

formula

If we organize the components, i.e. rows & columns, in the matrix well, the equivalence classes can be visually represented as the blocks on the 0-1 matrix along the diagonal.  It sounds like a very elegant solution, but the challenge is to implement the multiplication efficiently for our `bit_table`.

**Comment by kthielen** [comment]
This is very promising.  We are finding the connected components in the graph of state equivalence as you say.

The approach with path compression is similar to the unionfind implementation of unification for type inference (where we use set representatives and path compression to speed up unification steps).  Maybe there’s an opportunity to combine some of that code.

Great work Kai, this must have taken some patience.  It will really help in cases like HBFM where we produce large pattern match tables that include regular expressions.

**Comment by chenkai036** [comment]
> This is very promising. We are finding the connected components in the graph of state equivalence as you say. The approach with path compression is similar to the unionfind implementation of unification for type inference (where we use set representatives and path compression to speed up unification steps). Maybe there’s an opportunity to combine some of that code.

Thanks @kthielen, added #283 in the backlog.  I will also give a try on the idea of matrix multiplication.

**Comment by chenkai036** [comment]
> nice job. Then we just have to replace the double loop
> for (size_t i = 0; i < eqStates.size(); ++i) {
> for (size_t j = 0; j < i; ++j) {
> }}
> by a hash using updated mappings as keys, and we will get the optimum

yeh, I missed this at the first place.  Thanks @MichZia, that's also a very good point!

**Pull request merged**
