### PR TITLE
nix build for hobbes, courtesy of thmzlt

### PR DESCRIPTION
**Pull request by kthielen**
This is a work in progress, should resolve a few issues where stricter gcc settings are enabled.

### CODE REVIEW

**Comment by thmzlt** [comment]
Here is the diff I applied to get rid of some other unused result errors:

```diff
diff --git a/bin/hi/main.C b/bin/hi/main.C
index d684651..bd2da43 100644
--- a/bin/hi/main.C
+++ b/bin/hi/main.C
@@ -552,7 +552,9 @@ void runProcess(const std::string& cmd, std::ostream& out) {
     throw std::runtime_error("Unable to bind local pipe to STDOUT.");
   }

-  system(cmd.c_str());
+  int rc = system(cmd.c_str());
+
+  assert(rc == 0);

   dup2(ostdo, STDOUT_FILENO);
   close(pio[1]);
@@ -724,4 +726,3 @@ int main(int argc, char** argv) {
     return -1;
   }
 }
-
diff --git a/bin/hi/www.C b/bin/hi/www.C
index b9f28db..c445296 100644
--- a/bin/hi/www.C
+++ b/bin/hi/www.C
@@ -20,8 +20,8 @@ ssize_t sendfile(int toFD, int fromFD, off_t* o, size_t sz) {
 namespace hi {

 // blocking non-blocking write shorthand
-void write(int fd, const char* s)        { ::write(fd, s, strlen(s)); }
-void write(int fd, const std::string& s) { ::write(fd, s.c_str(), s.size()); }
+void write(int fd, const char* s)        { auto rc = ::write(fd, s, strlen(s)); assert(rc > 0); }
+void write(int fd, const std::string& s) { auto rc = ::write(fd, s.c_str(), s.size()); assert(rc > 0); }

 // determine whether a file can be opened and read
 bool fileExists(const std::string& x) {
@@ -68,7 +68,7 @@ bool catPathToFSPath(const std::string& cat, const std::string& cpath, std::stri
   if (fileExists(*fsPath)) {
     return true;
   }
-
+
   *fsPath = exeDir() + "/../../common/www/" + cat + "/" + cpath;
   if (fileExists(*fsPath)) {
     return true;
@@ -529,4 +529,3 @@ WWWServer::VarBindingDescs* WWWServer::getVarBindingDescs() {
 }

 }
-
diff --git a/bin/hog/batchsend.C b/bin/hog/batchsend.C
index 7fb7d20..6337b32 100644
--- a/bin/hog/batchsend.C
+++ b/bin/hog/batchsend.C
@@ -258,7 +258,7 @@ struct BatchSendSession {
       destinations.push_back(Destination{localdir, hostport});
     }

-    // start from last segment in directory
+    // start from last segment in directory
     const auto paths = hobbes::str::paths(dir + "*/segment-*.gz");
     if (paths.size() > 0) {
       this->c = std::stoi(hobbes::str::rsplit(hobbes::str::rsplit(paths.back(), ".gz").first, "segment-").second);
@@ -315,7 +315,9 @@ struct BatchSendSession {
       for (const auto & destination : destinations) {
         // we should save the init message to a special file, else pick a generic segment file name
         std::string pubfilename = destination.localdir + "/" + ((this->c == 0) ? "init.gz" : segmentFileName(this->c));
-        link(this->tempfilename.c_str(), pubfilename.c_str());
+        int rc = link(this->tempfilename.c_str(), pubfilename.c_str());
+
+        assert(rc == 0);
       }
       unlink(this->tempfilename.c_str());
       ++this->c;
@@ -471,4 +473,3 @@ void pushLocalData(const hobbes::storage::QueueConnection& qc, const size_t sess
 }

 }
-
```

**Comment by kthielen** [comment]
Ah excellent!  Let me try that now, then I will post back to the PR for the final commit.  This nix script you've put together is pretty close to something I think we can use in travis-ci, too.

**Comment by kthielen** [comment]
Added those changes to the PR, finally got to the very end successfully!  :)

Thank you for all of this, we're much closer to getting into the nix ecosystem now!

**Comment by thmzlt** [comment]
Here is a branch with the default.nix and Travis CI set up: https://github.com/thmzlt/hobbes/pull/1

It should pass CI once this branch is merged.

**Comment by kthielen** [comment]
@smunix, @chenkai036 : I think that this change is good, doesn't change the behavior of anything, just gets us past some compile errors that @thmzlt hit when putting together a nix script for hobbes.

**Comment by kthielen** [comment]
Seems that travis-ci is stuck on something (after I squashed the PR commits).  I will try to kick it, see if I can get it to run tests again.  The tests did pass.

**Comment by kthielen** [comment]
OK, I merged Thomaz's nix target for travis-ci, looks like it's running now.

**Comment by thmzlt** [comment]
Cool, looks like the Nix build passed. I noticed it didn't run the tests like the other targets.

**Comment by kthielen** [comment]
I noticed that too, probably just needs a small change to run the test program after building.  Interesting that the nix build completed so quickly.

**Comment by thmzlt** [comment]
Test are now running in my branch after this commit: https://github.com/thmzlt/hobbes/pull/1/commits/d7d25b3d542e01354f67a6b8f97c1da5f7275050. The default make test target in Nix is `check` rather than `test`.

**Comment by kthielen** [comment]
Oh that's better than what I was trying (getting the result path and running the test program directly).

I put your changes into this PR.  I don't want to take credit for all of your work, so would be happy to retract this if you want to copy to your own PR.  If you do want to do that, Morgan Stanley wants a dco file in your first commit (I had to do this, you can see my file in the dco/ directory here), just to avoid legal trouble.

**Comment by thmzlt** [comment]
No problem. Feel free to merge.

If I can help in the future, I'll fill out the dco and open a proper PR.

**Pull request merged**
