### PR TITLE
adapt to versions of LLVM > 4

### PR DESCRIPTION
**Pull request by MichZia**
ported to LLVM 6.0

### CODE REVIEW

**Comment by kthielen** [comment]
Does this work?  There's a lot of interesting work to do on the back end still.

**Comment by smunix** [comment]
No, it didn't work. This caused hi to crash within LLVM. The issue Michel is having is, he can't get Hobbes to link on Mint Linux. I've also seen a similar issue with Gentoo, but haven't had enough a chance to dig into it yet.
We need to refactor our APIs to interact with LLVM in a more version-agnostic way, and make it easy to upgrade across LLVM versions.

**Comment by kthielen** [comment]
Ah, well they keep changing the JIT in LLVM so it's been difficult to work through major restructuring in each new LLVM version (and performance seems to have become progressively worse with new versions).

It might be simpler all around for us to implement our own code generator.  I'm doing work in that direction.

**Comment by smunix** [comment]
BTW, #69 was tackling this very same issue, but wasn't completed.

> It might be simpler all around for us to implement our own code generator. I'm doing work in that direction.

This is great !

**Pull request closed without merging**
