### PR TITLE
#294, refactor CMakeLists.txt

### PR DESCRIPTION
**Pull request by smunix**

### CODE REVIEW

**Comment by smunix** [comment]
This is to test that travis is able to find llvm@8. Do not merge.

**Comment by kthielen** [comment]
Thank you sir!  I've got this reproduced on my laptop now and will work on testing with LLVM 8.

**Comment by chenkai036** [comment]
quite slow in responding this... I was playing `llvm-config` and I think we can make CMakeLists.txt less verbose by using it.  In fact, my local change takes about 10 lines to enable llvm6 on Linux.  It's worth to try it out with llvm8 and/or on OSX.

**Comment by kthielen** [comment]
We used to use it a long time ago, but IIRC it included too many libs, and I think that the cmake libs are supposed to do a similar thing.

I think it’s great if you can get it to work reliably, these LLVM build issues are a pain.  Actually there are a bunch of things about LLVM that are painful.  :T

**Comment by smunix** [comment]
> quite slow in responding this... I was playing `llvm-config` and I think we can make CMakeLists.txt less verbose by using it. In fact, my local change takes about 10 lines to enable llvm6 on Linux. It's worth to try it out with llvm8 and/or on OSX.

pls submit your changes to fix.llvm-compat branch, so we can merge support for llvm@6

**Comment by chenkai036** [comment]
As a tangible solution (not blocking some internal work), I pushed a pull request #299 to build hobbes only on llvm6.  JIT guru Hector has helped resolving quite a few issues during the upgrade, Salute!!

**Comment by smunix** [comment]
k, closing this as I'm not longer working on it

**Pull request closed without merging**
