### PR TITLE
fix compiler warnings

### PR DESCRIPTION
**Pull request by libow**

### CODE REVIEW

**Comment by kthielen** [comment]
Looks like there's a compile error on Linux.  What was the warning that you wanted to eliminate?  Should we have changed the build settings to treat it as an error?  I've been doing that lately to make it easier to integrate hobbes with programs with stricter compiler settings.

**Comment by libow** [comment]
when compiling hobbes with gcc 8.0. 
compiler generates following errors:
#1 : error: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘struct std::pair<unsigned int, long unsigned int>’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Werror=class-memaccess]
#2 httpd.C:72:7: error: this statement may fall through [-Werror=implicit-fallthrough=]

**Comment by kthielen** [comment]
I fixed the one in httpd in my latest PR.  I don't know where the memcpy error is coming from, but if we can't memcpy into an std::pair<int,long> then there's going to be some really awkward code rewrites I think.  Do you know why that's not allowed?  There's probably some good thinking behind it, just curious to know what it is.

**Comment by kthielen** [comment]
I think that at least some of this has been addressed in the meantime.  This PR has been sitting around for a long time in a broken state so I guess I will just close it.  But if you use gcc 8 and want to use this there, maybe this should be reopened (might even be worth adding a docker image for gcc 8 to the build list).

**Pull request closed without merging**
