### PR TITLE
add Map Functor instance for maybe

### PR DESCRIPTION
**Pull request by smunix**

### CODE REVIEW

**Comment by smunix** [comment]
A convenience change to turn a ()+a type into a Functor

**Comment by kthielen** [comment]
It'll be handy to do monad comprehensions on maybe values.

**Comment by smunix** [comment]
> It'll be handy to do monad comprehensions on maybe values.
I have a working implementation of it, but, in the case of multiple selections/conditions, the definition of mflatten escapes from maybe monad into the list one:
`mflatten :: (MFlatten a b) => (a) -> [b]`
It's possible to change this and make MFlatten more generic though.

**Comment by chenkai036** [comment]
@smunix shall we have a test to get the code exercised, or is there already any ?

**Comment by smunix** [comment]
closing this, as it's addressed in #290

**Pull request closed without merging**
