### PR TITLE
add pragma option in flex/bison prologue/epilogue

### PR DESCRIPTION
**Pull request by chenkai036**
This change add compiler pragma directives in flex/bison rules, avoiding
the sections being accidentally removed when re-generating the parser
rules.  flex 2.6.4 and bison 3.3.2 are used in generating the parser
code, with which most of the pragma options can be safely turned off.

### CODE REVIEW

**Comment by kthielen** [comment]
Nice, this parser is an area where the project could use improvement.  Bison was an expedient choice six years ago when the syntax of hobbes wasn’t a focus (other than looking somewhat like Haskell), but it has some issues like this.

It looks like the generated code has more differences than I’d expect (not just inserting the pragmas to disable C cast warnings).  Have you been able to test this with eg lgv to verify that old code still parses?

**Comment by chenkai036** [comment]
The major changes come from flex whereas bison changes are fine.  I tried all available flex versions I can find (due to the restricted environments) but none of the generated code seems perfectly compatible.  It's a good idea to run with lgv, we'll see if it causes any issue.

**Comment by chenkai036** [comment]
Loading lgv appears to be fine.

**Comment by kthielen** [comment]
> Loading lgv appears to be fine.

Ship it! 😄

**Pull request merged**
