### PR TITLE
preserve and chain writer CBs in fregion::writer

### PR DESCRIPTION
**Pull request by smunix**

### CODE REVIEW

**Comment by chenkai036** [comment]
@smunix is there such use-case to cascade the write callback?

**Comment by smunix** [comment]
> @smunix is there such use-case to cascade the write callback?

yes, transactional log (recordOrdering) breaks without this change.

**Comment by kthielen** [comment]
Are you sure that it breaks without the change?  Maybe we should have a test to validate it I guess.

As I recall, this would normally result in one write CB per wseries (in order to correlate recording across all of them), which doesn't need multiple callbacks in a single wseries.

**Comment by smunix** [comment]
Without this change, the following is broken:
`
writer w = ...;
auto &s1 = w.series<T1>();
auto &s2 = w.series<T2>();
w.recordOrdering("log", s1, s2);
s1.setWriteCB([](uint64_t){
  acmeShootMissile();
});
`

**Comment by kthielen** [comment]
But you can't do `w.series<T1>();` without a name right?  And if you do `auto& s1=w.series<T1>("x"); auto& s2=w.series<T2>("y");` then `w.recordOrdering("log",s1,s2);` works without your change right?

**Comment by kthielen** [comment]
(i.e.: because the callback is on the series, different series having just one callback is sufficient for `recordOrdering` to work correctly for recording a correlation series between all of them)

**Comment by kthielen** [comment]
Basically, the use-case for multiple callbacks per series would be multiple correlation sequences where the included set of series between them might overlap (though historically we haven't ever had such a use-case, it's possible that we might want it).

**Comment by salumup** [comment]
> `w.series<T1>()` requires a name...
Yes, it was just a snippet of code to convey the idea of how I'm using the APIs here

> (i.e.: because the callback is on the series, different series having just one callback is sufficient for `recordOrdering` to work correctly for recording a correlation series between all of them)

Agreed, yes. Writing w.recordOrdering() at the end works only for an astute software engineer, but not for the careless developer I can be at times (one who relies on the APIs to do the right thing irrespective of the order in which they get invoked).

In one of my apps, I'm using this writeCBs to keep track of the offsets  at which I write some of my data.

**Comment by kthielen** [comment]
Ah that's a good use-case too, hadn't thought of that.  :)

**Pull request merged**
