### PR TITLE
compute liveness and interference more quickly and with less memory

### PR DESCRIPTION
**Pull request by kthielen**
This addresses some issues found when compiling very large programs.

Previously, liveness sets would allocate much more memory than necessary (with one var set per instruction).  Now we use a much more efficient method, storing var sets just at join points in the control flow graph and interpolating liveness across straight-line instructions.  A new test is added to verify equivalence with the old/inefficient method of liveness calculation on random programs.

Also for extremely large programs, it was possible to silently truncate IDs for the 2D square interference bit matrix (used in register allocation) at the limit of int32 representation.  This change detects such truncation with an error and also extends these indexes to 64 bits to allow such large programs.

### CODE REVIEW

**Comment by kthielen** [comment]
It looks like this builds and runs as expected on Linux.  For some reason the automated build fails on macOS due to a travis-ci package error.  I will follow up with those guys, though FWIW it builds/runs fine on my laptop.

**Comment by kthielen** [comment]
Tried to update to `llvm@8` (which works on my macbook), but travis-ci killed the job because it wound up building cmake and llvm from scratch and exceeded some maximum log length setting on their end (?).

I'm starting to feel like macOS support is more trouble than it's worth ...

**Comment by chenkai036** [comment]
> Tried to update to `llvm@8` (which works on my macbook), but travis-ci killed the job because it wound up building cmake and llvm from scratch and exceeded some maximum log length setting on their end (?).
> 
> I'm starting to feel like macOS support is more trouble than it's worth ...

it seems that moving to default osx image prevents travis-ci from pulling & rebuilding everything from scratch: https://github.com/chenkai036/hobbes/pull/7/files

**Comment by kthielen** [comment]
Thanks Kai!  I put your `.travis.yml` changes in here and all stages pass.  The main change here has to do with this alternative compiler backend, which we aren't using so much in hobbes itself at the moment (but have some other large uses elsewhere).

Anyway, it's good to keep macOS support.

**Comment by kthielen** [comment]
I get the "squash and merge" button but when I click on it, nothing happens.  Between this and the infinite progress indicator when assigning reviewers, I feel like github is trolling me.  ;)

**Pull request merged**
