### PR TITLE
#292, fix mac osx build with llvm@35

### PR DESCRIPTION
**Pull request by smunix**
addresses #292

### CODE REVIEW

**Comment by kthielen** [comment]
Are we going to merge this?

**Comment by chenkai036** [comment]
I think that #299 has already covered this in a different way?

**Comment by kthielen** [comment]
Oh, then I guess this PR can be closed.  But wait, why did my PR yesterday (https://github.com/Morgan-Stanley/hobbes/pull/306#issuecomment-559879579) fail when building llvm@4 then?

**Comment by chenkai036** [comment]
> Oh, then I guess this PR can be closed. But wait, why did my PR yesterday ([#306 (comment)](https://github.com/Morgan-Stanley/hobbes/pull/306#issuecomment-559879579)) fail when building llvm@4 then?

looks like a different cause, where llvm@4 has been deleted from brew on travis-ci.  Would you update llvm to a newer version for osx build?

**Comment by andrewnc** [comment]
I know this is a stale PR, but I figured this was the appropriate place to comment. 

I have been trying to build hobbes on macOS Mojave for a few days with little success. 

I have tried LLVM 3.5, 3.9, 4.0, 6.0, 8.0, 9.0 but they all have different issues that come up. 

I tried finding the supported version of LLVM, but it was unclear. 

I would very much appreciate advice on how to build on my mac. 

ps. I also tried building on Linux llvm6 with no success. I think at this point, in my inexperience, I'm missing something pretty critical.

**Comment by kthielen** [comment]
> I know this is a stale PR, but I figured this was the appropriate place to comment.

Hi andrew, any place is a good place to comment!  Actually this PR seems to be relevant, though also seems to be stale as you say.  Also feel free to open an issue if you'd like, we aren't mean about it.  :)

> I have been trying to build hobbes on macOS Mojave for a few days with little success.
> 
> I have tried LLVM 3.5, 3.9, 4.0, 6.0, 8.0, 9.0 but they all have different issues that come up.

How are you trying LLVM versions and what cmake version are you using?  I hit a few issues going to macOS Mojave a while back myself, the upgrade broke a few other things (e.g. macports, if you use that package manager).

It's a little bit to wade through, but the travis-ci config script in the hobbes repo has recipes for installing and building hobbes on macOS and Linux targets (https://github.com/Morgan-Stanley/hobbes/blob/master/.travis.yml), and this is what is used to build and test/verify hobbes with each pull request.

For macOS targets, it looks like this (using the homebrew package manager for macOS -- https://brew.sh):

```
DEPS="${DEPS} readline llvm@6"
brew update && brew install -v ${DEPS}

LLVM_DIR=/usr/local/opt/llvm@6/lib/cmake/llvm/
mkdir build && cd build/ && cmake .. && make && make test
```

That should get LLVM 6 (chosen arbitrarily, I've actually found that the earlier LLVM JIT is better, though that's a long story), then invokes cmake to generate a local makefile, and then make to build it.

I don't think that the JIT engine has been a priority for the LLVM maintainers, and I've frequently considered moving hobbes to a custom backend just to drop the dependency (there is actually a small custom backend implemented in hobbes: https://github.com/Morgan-Stanley/hobbes/tree/master/include/hobbes/mc).  It would definitely simplify building and make the project very lightweight and easy to include elsewhere.  Probably if I get a few folks interested in that option, I'll put in the elbow grease to do it.  :D

**Comment by kthielen** [comment]
BTW, thomaz also got us building through nix, if you're familiar with that system it should be very easy (I have less experience with nix than he does but I need to learn more, I know some other folks using hobbes and nix).

Also if you hit errors and you're not sure to go with them, maybe start an issue here and copy/paste the specific details.  It might be something that we can work through together (like e.g. something specific to Mojave).

If you'd rather not go through that in public for whatever reason, please feel free to send me a private email.  I collaborate with a lot of people via email already, it's no problem.  :)

**Comment by andrewnc** [comment]
That did the trick! I'm not sure what was missing from the llvm6 I downloaded and built, but the brew version worked like a charm. 

It took a while to build, but it seems like it's working (the `hi` interpreter launches fine). 

Thank you for walking me through the proper dependencies. Cheers!

**Comment by kthielen** [comment]
Excellent!

**Pull request closed without merging**
