### PR TITLE
Remove hardcoding of hogstat path in Hog test

### PR DESCRIPTION
**Pull request by hstalker**
Use the standard environment variables to appropriately set the path for domain sockets and hogstat.db, pass the appropriate -m option to Hog, and also to fetch the hogstat.db path for testing. In addition remove the unnecessary hogstat.db cleanup tests.

### CODE REVIEW

**Comment by kthielen** [comment]
Looks like hog tests fail on Linux (they don't run on macOS).  Any idea what those failures mean?

**Comment by hstalker** [comment]
It works fine under my local machine when tested with HOBBES_STORE_DIR unset and HOBBES_STORE_DIR set to some custom directory, so as of now we are unsure. I suspect that it has something to do with accessibility of the /var/tmp directory (potentially under docker?), but it's hard to tell. The oddest thing about the failures is that all the tests are failing despite me having not really changed most of them at all (unless somehow adding the -m switch to do exactly what it was already doing would cause a failure somehow).

**Comment by kthielen** [comment]
I had to merge the latest (unrelated) changes into your branch, so the travis-ci tests will run again.  We'll see what happens.

I noticed that the Hog tests failed, but also the python tests failed with a complaint about a file '/tmp/hdb-blahblah-0.py' not being available to read, so maybe something happened with the temp directory here.

**Comment by hstalker** [comment]
Hmm, now multiple builds are timing out completely on the Hog tests. Very strange.

**Comment by chenkai036** [comment]
It's worth to separate hogstat.db per test for better support in diagnosis.  I've sent another PR for the change and it seems passing the travis-ci builds.

**Comment by kthielen** [comment]
Looks like there's a merge conflict now.  Do we take the one that sets the stats file path to cwd?

**Comment by hstalker** [comment]
Kai's PR looks good and should be preferred over mine here. One part of that PR I'm wary about however is the fact that we now don't turn off recovery by default with those changes, which may have unforeseen consequences in some of the Hog tests later on, and I suspect the fact we now isolate the statfiles may simply be masking said potential issues. For instance, we might restart a Hog instance without intending to have it recover, but we have no way to turn it off. If we conclude that's not a problem, then I'll close this PR.

**Comment by chenkai036** [comment]
Most of the tests were introduced before hogstat.db, so I think the stat file shall be transparent to them functionality-wise.  IMO we shall group hogstat.db separately so batchrecv & batchsend doesn't write to the same file causing data corruption.  For testing, I think that it's reasonable to add back the 'resume' option, so that we can easily write tests for clean bounce if needed.

**Comment by hstalker** [comment]
Agreed. Either way, I think this particular PR is dead in the water now, so I'll be closing it.

**Pull request closed without merging**
